### PR TITLE
Made it work on Symfony 3.

### PR DESCRIPTION
**Pull request by cinam**
A small fix for Symfony3

### CODE REVIEW

**Comment by cinam** [comment]
Code is formatted according to PSR-2, removed all trailing whitespaces.

**Comment by fogs** [comment]
Hi cinam,

Thanks for contributing to this project. Will your change brake compatibility for Symfony 2.x?

Thanks,
fogs

**Comment by cinam** [comment]
Hi,

No, compatibility won't be broken - just checked it on 2.8.

I just added additional fixes, on 3.1 you need to quote yaml entries starting with "@".

**Comment by cinam** [comment]
Thanks

**Pull request merged**
